[tool.commitizen]
name = "cz_conventional_commits"
annotated_tag = true
gpg_sign = true
tag_format = "v$version"
update_changelog_on_bump = true
changelog_merge_prerelease = true
version = "6.0.0b0"
version_provider = "commitizen"
version_scheme = "pep440"
version_files = [
    "server/pyproject.toml:version",
]
pre_bump_hooks = [
    "prek run --all-files || true",
]
post_bump_hooks = [
    "git push origin master $CZ_POST_CURRENT_TAG_VERSION"
]
